# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: file-contents-sorter
      - id: mixed-line-ending
        args: [--fix=lf]
    stages: [commit-msg]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: Check commit message using commitlint
        description: >
          Lint commit message against @commitlint/config-conventional rules
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional@17.4.4"]
        args: [--config, .ci/commitlint.config.js]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
        files: ^.*\.(sh|bash|ksh)$
        args: [-e, SC1091]
        types: [shell]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict, -c, .ci/.yamllint.yaml, .]
        always_run: true
        pass_filenames: false

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
