# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
---
name: auto-update github-actions

on:
  # every day at midnight
  schedule:
    - cron: 0 0 * * 0
  # on demand
  workflow_dispatch: null
  workflow_call: null

permissions:
  pull-requests: write
  contents: write

jobs:
  autoupdate-gh-actions:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: '${{ secrets.GITHUB_TOKEN }}'
          skip_pull_request: true
