---
name: auto-update github-actions 

'on':
  # every day at midnight
  schedule:
    - cron: 0 0 * * 0
  # on demand
  workflow_dispatch: null
  workflow_call: null

permissions:
  pull-requests: write
  contents: read

jobs:
  gh-actions-autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: chinthakagodawita/autoupdate@v1.7.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
