# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
---
name: auto-update pre-commit

on:
  # every day at midnight
  schedule:
    - cron: 0 0 * * 0
  # on demand
  workflow_dispatch: null
  workflow_call: null

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-update-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - uses: browniebroke/pre-commit-autoupdate-action@main

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
