# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
---
name: labeler

on:
  workflow_call: null
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-size@v2
        id: size
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.stale_labels }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ${{ steps.size.outputs.new_label }}
      - uses: actions/labeler@v4
        id: triage