# -*- coding: utf-8 -*-
# vim: ft=yaml
# yamllint disable rule:truthy
---
name: ci convanional commits PR title lint
on:
  workflow_call:
    inputs:
      subject-types:
        description: |
          A list of subject types to lint. If not provided, all types will be linted.
        required: false
        default: |
          fix
          feat
          build
          chore
          ci
          docs
          perf
          refactor
          revert
          style
          test
        type: string
      node-version:
        description: |
          The node version to use. If not provided, the latest version will be used.
        required: false
        default: 16
        type: number

permissions:
  pull-requests: write
  contents: read

jobs:
  conventional-commits-pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: ${{ github.event.inputs.subject-types }}
      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the
            [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
            and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```
      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
