# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: ci repo initializer

'on':
  # every day at midnight
  schedule:
    - cron: 0 0 * * 0
    # on demand
  workflow_dispatch: null
  workflow_call:
    inputs:
      artifact_name:
        description: name of the artifact to use
        required: false
        type: string
        default: source-code
      artifact_upload:
        description: upload artifact
        required: false
        type: boolean
        default: true
      runs-on:
        description: Select github runner based on labels, default is "['ubuntu-latest']"
        required: false
        type: string
        default: "['ubuntu-latest']"
    outputs:
      version:
        description: Semantic version of the repository, based on the privious tag
        value: ${{ jobs.init.outputs.version }}
      artifact:
        description: name of the artifact
        value: ${{ inputs.artifact_name }}

permissions:
  contents: read

jobs:
  init:
    name: setup artifacts and version
    runs-on: ${{ fromJson(inputs.runs-on) }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get version
        id: version
        run: |
          echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact_upload }}
        with:
          name: ${{ inputs.artifact_name }}
          path: ./
