# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: pre-commit

permissions:
  contents: read
  pull-requests: read

'on':
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:
    inputs:
      python_version:
        description: Python version to use for pre-commit
        required: false
        type: string
        default: '3.10'
      dart_version:
        description: Dart version to use for pre-commit
        required: false
        type: string
        default: ''

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Set up Dart
        if: ${{ inputs.dart_version != '' }}
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ inputs.dart_version }}
      - uses: pre-commit/action@v3.0.1
