# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: release
"on": workflow_dispatch

permissions:
  # To Push Changes to the Repository
  contents: write
  # To Update GitHub Action workflow files
  actions: write
  # To Create Pull Requests
  pull-requests: write
  # to enable use of OIDC for npm provenance
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.0
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
            conventional-changelog-eslint@3.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
