# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: release
"on": workflow_dispatch

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: ghcr.io/semantic-release:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config --global --add safe.directory /__w/template-repository/template-repository &&
          semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAINTAINER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
