# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: release
"on": workflow_dispatch

permissions:
  # to be able to publish a GitHub release
  contents: write
  # to be able to comment on released issues
  issues: write
  # to be able to comment on released pull requests
  pull-requests: write
  # to enable use of OIDC for npm provenance
  id-token: write

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: ghcr.io/semantic-release:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: |
          git config --global --add safe.directory /__w/ci/ci &&
          semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
